export const recipesConstants = {
  GET_RECIPIES_INFO_REQUEST: "GET_RECIPIES_INFO_REQUEST",
  GET_RECIPIES_INFO_SUCCESS: "GET_RECIPIES_INFO_SUCCESS",
  ADD_FILTER_INGREDIENT: "ADD_FILTER_INGREDIENT",
  REMOVE_FILTER_INGREDIENT: "REMOVE_FILTER_INGREDIENT",
};
